# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LloydsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  # Pods for LloydsTest

  target 'LloydsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LloydsTestUITests' do
    # Pods for testing
  end

end
